oracle:
  identity:
    # 身份配置文件的文件名匹配规则.
    pattern: '.+\.oracle\.ini$'
    # 身份配置文件夹路径.
    location: './identity/'
  script:
    # 脚本文件夹路径.
    location: './scripts/'
  ssh:
    # SSH 认证文件存储路径.
    identityPath: './config/ssh-auth.json'
    firstConnection:
      # 首次连接认证策略
      # 支持 confirm(询问) accept(接受) reject(拒绝)
      authenticationPolicy: 'confirm'
